### ISSUE TITLE
Rally 2.1.0 ignoring client options that worked in Rally 2.0.1

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/rally-eventdata-track#107]
When a query_index_prefix is specified in 2.1.0 the number_of_shards is ignored.

For example this works in 2.0.1 but not 2.1.0:

esrally race --target-hosts=cluster-load-balancer:9200 --kill-running-processes --track-path rally-eventdata-track/eventdata --pipeline=benchmark-only --client-options=“use_ssl:true,verify_certs:false,basic_auth_user:‘elastic’,basic_auth_password:passwordgoeshere” --track-params=“bulk_indexing_clients:100,bulk_indexing_iterations:50000,number_of_shards:5,number_of_replicas:1,query_index_prefix:custom_rally_benchmark”

And this works in both 2.0.1 and 2.1.0:

esrally race --target-hosts=cluster-load-balancer:9200 --kill-running-processes --track-path rally-eventdata-track/eventdata --pipeline=benchmark-only --client-options=“use_ssl:true,verify_certs:false,basic_auth_user:‘elastic’,basic_auth_password:passwordgoeshere” --track-params=“bulk_indexing_clients:100,bulk_indexing_iterations:50000,number_of_shards:5,number_of_replicas:1”

**Comment by danielmitterdorfer** [comment]
@ebadyano would you be able to look into this?

**Comment by ebadyano** [comment]
So this seems to be due to this change: https://github.com/elastic/rally-eventdata-track/pull/89.

@danielmitterdorfer Should it be `query_index_prefix` instead in your change? Also [README](https://github.com/elastic/rally-eventdata-track/blob/master/README.md#track-parameters-supported-by-all-challenges) only mentions `query_index_prefix` parameter..

**Comment by danielmitterdorfer** [comment]
> So this seems to be due to this change: #89.

@ebadyano can you please provide more detail about your reasoning, i.e. *why* do you think the behavior described in the description is caused by that PR?

**Comment by ebadyano** [comment]
@danielmitterdorfer sorry, should've been more specific. I can reproduce the issue with the change and it goes away with the commit of eventdata-track right before that. Also, the issue goes away if instead of `query_index_prefix:custom_rally_benchmark` I use `index_prefix:custom_rally_benchmark`
