### ISSUE TITLE
node.roles with data_hot (and others) rather than node.data: true causes a divide by zero error in nodestorage_runner

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/rally-eventdata-track#108]
https://github.com/elastic/rally-eventdata-track/blob/9ad0d4824938ed07ebf031e072ef3d2d7bf4ca19/eventdata/runners/nodestorage_runner.py#L47

That needs to get updated with the additional values in https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html

At least h and s are valid and possibly c, f, and w should be checked too.

**Comment by danielmitterdorfer** [comment]
@ebadyano would you be able to look into this?
